Repository IIS-ZPI/ZPI2024_zaoczni_NBP_Crasher, pull requests merged in 2025-01, with the labels that each got.

#46 Frontend implementation (base)
  .gitignore
  compose.yml
  frontend/.dockerignore
  frontend/.editorconfig
  frontend/.gitignore
  frontend/.vscode/extensions.json
  frontend/.vscode/launch.json
  frontend/.vscode/tasks.json
  frontend/Dockerfile
  frontend/README.md
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.scss
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
  frontend/src/app/app.routes.ts
  frontend/src/assets/.gitkeep
  frontend/src/favicon.ico
  frontend/src/index.html
  frontend/src/main.ts
  frontend/src/styles.scss
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.spec.json
Labels: enhancement

#47 Charts & table implementation
  README.md
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
  frontend/src/app/app.model.ts
  frontend/src/index.html
Labels: enhancement

#48 add numerical statisticts summary
  .github/workflows/run-frontend-tests.yml
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
  frontend/src/styles.scss
Labels: enhancement

#52 Fix default time frame (range)
  .github/workflows/run-backend-tests.yml
  README.md
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.config.ts
Labels: requirement fix, fix

#50 Integration with nbp api
  .gitignore
  README.md
  backend/Dockerfile
  backend/calculations/calculations.py
  backend/fastAPI.py
  backend/requester.py
  backend/requirements.txt
  backend/routes/stats_routes.py
  backend/routes/stats_routes_responses.py
  backend/tests/calculations_test.py
  backend/tests/stats_routes_test.py
  compose.yaml
Labels: enhancement

#53 Frontend <-> backend integration
  frontend/README.md
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
  frontend/src/app/app.model.ts
  frontend/src/app/models/error.model.ts
  frontend/src/app/services/base/base.errors.ts
  frontend/src/app/services/base/base.service.spec.ts
  frontend/src/app/services/base/base.service.ts
  frontend/src/app/services/stats/stats.errors.ts
  frontend/src/app/services/stats/stats.model.ts
  frontend/src/app/services/stats/stats.service.spec.ts
  frontend/src/app/services/stats/stats.service.ts
  frontend/src/environments/environment.production.ts
  frontend/src/environments/environment.ts
  frontend/src/main.ts
Labels: enhancement, Sprint 1

#58 Fix frontend api calls to localhost
  frontend/src/environments/environment.production.ts
Labels: bug

#59 fix single dominant (mode) printing
  README.md
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
Labels: fix

#62 Fix CORS configuration
  backend/fastAPI.py
Labels: fix

#67 add min date from limit
  frontend/angular.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
Labels: enhancement

#71 add cutting request into smaller chunks
  backend/requester.py
  backend/requirements.txt
  backend/routes/response_merge.py
  backend/routes/stats_routes.py
  backend/tests/stats_routes_test.py
Labels: fix

#75 add rate limiting
  backend/fastAPI.py
  backend/limiter.py
  backend/requirements.txt
  backend/routes/stats_routes.py
Labels: enhancement

#76 74 506 currencies validation error
  README.md
  backend/routes/stats_routes.py
Labels: fix

#60 Docs - application handover
  README.md
  docs/Activity/Activity.pdf
  docs/Activity/Activity.png
  docs/Activity/Activity.vpd
  docs/Architecture/Architecture.pdf
  docs/Architecture/Architecture.png
  docs/Architecture/Architecture.vpd
  docs/Code/Backend/Backend documentation.docx
  docs/Code/Backend/Backend documentation.pdf
  docs/Code/Backend/NBP Crasher.pdf
  docs/Code/Frontend/Frontend documentation.docx
  docs/Code/Frontend/Frontend documentation.pdf
  docs/Component/Component.pdf
  docs/Component/Component.png
  docs/Component/Component.vpd
  docs/Raports/Raport 1/Raport 1.docx
  docs/Raports/Raport 1/Raport 1.pdf
  docs/Raports/Raport 2/Raport 2.docx
  docs/Raports/Raport 2/Raport 2.pdf
  docs/Raports/Raport 3/Raport 3.docx
  docs/Raports/Raport 3/Raport 3.pdf
  docs/Raports/Raport 4/Raport 4.docx
  docs/Raports/Raport 4/Raport 4.pdf
  docs/Raports/Raport FINAL/Raport FINAL.docx
  docs/Raports/Raport FINAL/Raport FINAL.pdf
  docs/Sequence/SEQUENCE.pdf
  docs/Sequence/SEQUENCE.png
  docs/Sequence/SEQUENCE.vpd
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
  frontend/src/app/app.model.ts
  frontend/src/app/services/base/base.service.ts
  frontend/src/app/services/stats/stats.errors.ts
  frontend/src/app/services/stats/stats.model.ts
  frontend/src/app/services/stats/stats.service.ts
Labels: documentation

#80 add chart labels
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.config.ts
Labels: enhancement
